--- 
jobs: 
  build_and_deploy: 
    env: "REACT_APP_API_KEY='${{ secrets.REACT_APP_API_KEY }}' REACT_APP_AUTH_DOMAIN='${{ secrets.REACT_APP_AUTH_DOMAIN }}' REACT_APP_PROJECT_ID='${{ secrets.REACT_APP_PROJECT_ID }}' REACT_APP_STORAGE_BUCKET='${{ secrets.REACT_APP_STORAGE_BUCKET }}' REACT_APP_MESSAGING_SENDER_ID='${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}' REACT_APP_APP_ID='${{ secrets.REACT_APP_APP_ID }}'' REACT_APP_MESUREMENT_ID='${{ secrets.REACT_APP_MESUREMENT_ID }}'"
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        run: "npm install"
      - 
        run: "npm run build"
      - 
        uses: FirebaseExtended/action-hosting-deploy@v0
        with: 
          channelId: live
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIR_RECIPES_EABA0 }}"
          projectId: fir-recipes-eaba0
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
name: "Deploy to Firebase Hosting on merge"
? "on"
: 
  push: 
    branches: 
      - master
